version: "3.1"

services:
    note-postgres:
        env_file:
            - .env
        container_name: note-postgres
        image: postgres:alpine
        environment:
            - POSTGRES_USER=${_POSTGRES_USER}
            - POSTGRES_PASSWORD=${_POSTGRES_PASSWORD}
            - POSTGRES_DB=${_POSTGRES_DB}
        ports:
            - "5100:5432"
    note-app-backend:
        env_file:
            - .env
        container_name: note-app-backend
        image: note-app-backend
        depends_on:
            - note-postgres
        environment:
            - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres:5432/noteapp
            - FRONTEND_URL=none
            - GOOGLE_CLIENT_ID=none
            - GOOGLE_CLIENT_SECRET=none
        build:
            context: .
            dockerfile: Dockerfile
        ports:
            - "82:8080"
