server:
    port: 8080

spring:
    datasource:
        url: ${SPRING_DATASOURCE_URL}
        username: ${_POSTGRES_USER}
        password: ${_POSTGRES_PASSWORD}

    jpa:
        hibernate:
            ddl-auto: create-drop
        show-sql: true
        properties:
            hibernate:
                dialect: org.hibernate.dialect.PostgreSQLDialect
                format_sql: true
