# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy JAR app to Azure Web App - NoteApp-dev

on:
    push:
        branches:
            - main
    workflow_dispatch:

jobs:
    test-app-with-gradle:
        runs-on: ubuntu-latest

        services:
            note-postgres:
                image: postgres:alpine
                env:
                    POSTGRES_USER: postgres
                    POSTGRES_PASSWORD: none
                    POSTGRES_DB: noteapp
                ports:
                    - "5100:5432"
                options: --name note-postgres
        steps:
            -   uses: actions/checkout@v4

            -   name: Set up JDK 17
                uses: actions/setup-java@v3
                with:
                    java-version: '17'
                    distribution: 'temurin'

            -   name: Setup python
                uses: actions/setup-python@v4
                with:
                    python-version: '3.10'

            -   name: Update Project Version using Python Script
                run: python note-app-backend/src/main/resources/update_version.py

            -   name: Setup Gradle
                uses: gradle/gradle-build-action@v2
                env:
                    SPRING_DATASOURCE_URL: jdbc:postgresql://localhost:5100/noteapp
                    POSTGRES_USER: postgres
                    POSTGRES_PASSWORD: none
                    POSTGRES_DB: noteapp
                    FRONTEND_URL: http://localhost:4200
                    GOOGLE_CLIENT_ID: none
                    GOOGLE_CLIENT_SECRET: none
                with:
                    gradle-version: '8.2'
                    arguments: build
                    build-root-directory: note-app-backend

            -   name: Clean not worthy jar
                run: rm -rf note-app-backend/build/libs/*-plain.jar

            -   name: Upload artifact for deployment job
                uses: actions/upload-artifact@v3
                with:
                    name: NoteApp
                    path: '${{ github.workspace }}/note-app-backend/build/libs/note-app-backend-\d+.\d+.\d+.jar'

    deploy-dev:
        runs-on: ubuntu-latest
        needs: test-app-with-gradle
        environment:
            name: 'Development'
            url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

        steps:
            -   name: Download artifact from build job
                uses: actions/download-artifact@v3
                with:
                    name: NoteApp

            -   name: Deploy to Azure Web App
                id: deploy-to-webapp
                uses: azure/webapps-deploy@v2
                with:
                    app-name: 'NoteApp-dev'
                    slot-name: 'Production'
                    package: '*.jar'
                    publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE_0A6263AF0FD040DBBF6D21AA2AAFA2DE }}
